"""S.U.N. (Stability, Uniqueness, Novelty) + Validity reward for OMatG-DNG-IRL.

This implements the multiplicative multi-objective reward of CRYSTAL (Coordinated Multi-Objective RL for
Crystal Generation) adapted to operate on structures generated by OMatG. Given a *group* (GRPO rollout) of
generated structures, it returns a scalar reward per structure:

    R(s) = r_stab(s) * r_nov(s) * r_div(s)   if  valid(s) and r_stab(s) > 0,  else 0.

Components (CRYSTAL Sec. 3):
  * Validity (gate): minimum interatomic distance >= 0.5 A and cell volume > 0.1 A^3 (V_struct), SMACT
    charge-neutrality (V_charge, a practical proxy for sum of formal charges = 0), and successful MLIP
    relaxation (V_relax).
  * Stability: relax with CHGNet, then a continuous reward r_stab in [0, 1] that is 1 for energy-above-hull
    <= 0, decays linearly to 0 over (0, 0.1] eV/atom, and is 0 above 0.1 eV/atom. The "energy above hull" is
    provided by a pluggable StabilityScorer (default: self-consistent CHGNet formation energy w.r.t. elemental
    references; a cached Materials-Project convex hull can be dropped in).
  * Novelty (binary, on stable structures): CrystalNNFingerprint (structure) AND ElementProperty (composition)
    minimum L2 distance to the reference dataset both exceed thresholds.
  * Uniqueness/diversity (0..4, on stable structures): r_match (StructureMatcher within the group) + r_intra
    (element-set / stoichiometry repetition within the group) + r_inter (cross-rollout frequency, 0/1/2).

The expensive validity/fingerprint machinery is reused from ``omg.analysis.valid_atoms.ValidAtoms``.
"""
from collections import Counter
from dataclasses import dataclass, field
from pathlib import Path
from typing import List, Optional, Sequence, Dict
import warnings
import numpy as np
from ase import Atoms

from .stability import StabilityScorer, ElementalReferenceStability
from .novelty import NoveltyScorer


@dataclass
class StructureReward:
    """Per-structure reward breakdown."""
    valid: bool = False
    v_struct: bool = False
    v_charge: bool = False
    v_relax: bool = False
    e_above_hull: float = float("nan")
    r_stab: float = 0.0
    r_nov: float = 0.0
    r_div: float = 0.0
    r_match: float = 0.0
    r_intra: float = 0.0
    r_inter: float = 0.0
    reward: float = 0.0
    formula: str = ""


def _stability_reward(e_above_hull: float) -> float:
    """CRYSTAL Eq. (6): piecewise-linear stability reward from the energy above hull (eV/atom)."""
    if not np.isfinite(e_above_hull):
        return 0.0
    if e_above_hull <= 0.0:
        return 1.0
    if e_above_hull <= 0.1:
        return 1.0 - (e_above_hull) / 0.1
    return 0.0


class SUNReward:
    """
    Compute the CRYSTAL S.U.N. + validity reward for groups of generated structures.

    :param stability:
        StabilityScorer that maps relaxed structures to an energy above hull (eV/atom). Defaults to the
        self-consistent CHGNet elemental-reference formation energy.
    :param novelty:
        NoveltyScorer against a reference dataset (default: MP-20 train).
    :param relax_steps:
        Maximum number of CHGNet relaxation steps per structure.
    :param k_intra:
        Tolerance for element-set / stoichiometry repetition within a group (CRYSTAL K_intra). Defaults to 3.
    :param k_inter_low / k_inter_high:
        Thresholds for the three-tier cross-rollout frequency reward (CRYSTAL K_inter). Defaults to 3 and 5.
    :param structure_cutoff:
        Minimum allowed interatomic distance in Angstrom for structural validity. Defaults to 0.5.
    """

    def __init__(self, stability: Optional[StabilityScorer] = None, novelty: Optional[NoveltyScorer] = None,
                 relax_steps: int = 50, k_intra: int = 3, k_inter_low: int = 3, k_inter_high: int = 5,
                 structure_cutoff: float = 0.5, upper_narity_limit: Optional[int] = 5,
                 ablate: Optional[str] = None, verbose: bool = False) -> None:
        # ablate in {None, "stability", "novelty", "uniqueness"}: drop that factor (set it to 1) for the
        # CRYSTAL-style ablation study (Table 2). "stability" still relaxes for validity but ignores e_hull.
        self.stability = stability if stability is not None else ElementalReferenceStability(relax_steps=relax_steps)
        self.novelty = novelty if novelty is not None else NoveltyScorer()
        self.relax_steps = relax_steps
        self.k_intra = k_intra
        self.k_inter_low = k_inter_low
        self.k_inter_high = k_inter_high
        self.structure_cutoff = structure_cutoff
        self.upper_narity_limit = upper_narity_limit
        self.ablate = ablate
        self.verbose = verbose
        # Persistent cross-rollout frequency counters (CRYSTAL Eqs. 14-15): element-set and stoichiometry.
        self._freq_elements: Counter = Counter()
        self._freq_stoich: Counter = Counter()

    # ---- composition keys for diversity counters -------------------------------------------------
    @staticmethod
    def _element_key(structure) -> str:
        return "-".join(sorted(el.symbol for el in structure.composition.elements))

    @staticmethod
    def _stoich_key(structure) -> str:
        # Reduced integer formula, e.g. "Fe1Re7" -> "FeRe7" reduced.
        return structure.composition.reduced_formula

    def compute_group(self, atoms_list: Sequence[Atoms]) -> List[StructureReward]:
        """
        Compute rewards for one GRPO group (rollout) of generated structures.

        :param atoms_list:
            The generated structures of a single group as ASE ``Atoms``.

        :return:
            List of ``StructureReward`` (same order as ``atoms_list``).
        """
        from omg.analysis.valid_atoms import ValidAtoms
        n = len(atoms_list)
        results = [StructureReward() for _ in range(n)]

        # ---- 1. structural + charge validity and fingerprints (reuse ValidAtoms) -----------------
        with warnings.catch_warnings():
            warnings.simplefilter("ignore")
            valids = [ValidAtoms(a, structure_check_cutoff=self.structure_cutoff,
                                 upper_narity_limit=self.upper_narity_limit) for a in atoms_list]
        for i, va in enumerate(valids):
            results[i].formula = va.structure.composition.reduced_formula
            results[i].v_struct = bool(va.volume_valid and va.structure_valid)
            results[i].v_charge = bool(va.composition_valid)

        # Candidate structures that pass cheap validity gates -> relax + stability.
        cand_idx = [i for i in range(n) if results[i].v_struct and results[i].v_charge]
        cand_structures = [valids[i].structure for i in cand_idx]

        # ---- 2. relaxation + stability -----------------------------------------------------------
        relaxed_map: Dict[int, object] = {}
        if cand_structures:
            relax_out = self.stability.score(cand_structures)  # list of (e_above_hull, relaxed_structure, converged)
            for j, i in enumerate(cand_idx):
                e_hull, relaxed, converged = relax_out[j]
                results[i].v_relax = bool(converged)
                results[i].e_above_hull = float(e_hull)
                if converged:
                    results[i].r_stab = 1.0 if self.ablate == "stability" else _stability_reward(e_hull)
                    relaxed_map[i] = relaxed
                results[i].valid = bool(results[i].v_struct and results[i].v_charge and results[i].v_relax)

        # Stable set: valid and r_stab > 0 (CRYSTAL: S_stable = valid and e_hull <= 0.1).
        stable_idx = [i for i in cand_idx if results[i].valid and results[i].r_stab > 0.0]
        stable_structures = [relaxed_map[i] for i in stable_idx]

        # ---- 3. novelty (on stable, relaxed structures) ------------------------------------------
        if stable_structures:
            if self.ablate == "novelty":
                for i in stable_idx:
                    results[i].r_nov = 1.0
            else:
                nov_flags = self.novelty.is_novel(stable_structures)
                for j, i in enumerate(stable_idx):
                    results[i].r_nov = 1.0 if nov_flags[j] else 0.0

        # ---- 4. uniqueness / diversity (group-level, on stable structures) -----------------------
        if self.ablate == "uniqueness":
            for i in stable_idx:
                results[i].r_div = 1.0
        else:
            self._diversity(stable_idx, stable_structures, results)

        # ---- 5. final multiplicative reward ------------------------------------------------------
        for i in range(n):
            r = results[i]
            if r.valid and r.r_stab > 0.0:
                r.reward = r.r_stab * r.r_nov * r.r_div
            else:
                r.reward = 0.0
        return results

    def _diversity(self, stable_idx: List[int], stable_structures: List[object],
                   results: List[StructureReward]) -> None:
        """CRYSTAL Sec. 3.4: r_div = r_match + r_intra + r_inter, evaluated sequentially within the group."""
        from pymatgen.analysis.structure_matcher import StructureMatcher
        matcher = StructureMatcher()
        seen_structures: List[object] = []
        elem_counter: Counter = Counter()
        stoich_counter: Counter = Counter()
        for pos, i in enumerate(stable_idx):
            s = stable_structures[pos]
            ekey = self._element_key(s)
            skey = self._stoich_key(s)

            # r_match: 0 if any prior stable structure in this group matches s (same comp + geometry).
            matched = False
            for prev in seen_structures:
                if prev.composition.reduced_formula == s.composition.reduced_formula:
                    try:
                        if matcher.fit(prev, s):
                            matched = True
                            break
                    except Exception:
                        pass
            r_match = 0.0 if matched else 1.0

            # r_intra: 0 if element-set or stoichiometry repeats more than K_intra times within the group.
            r_intra = 0.0 if (elem_counter[ekey] > self.k_intra or stoich_counter[skey] > self.k_intra) else 1.0

            # r_inter: three-tier based on cross-rollout frequency f = max(freq_elements, freq_stoich).
            f = max(self._freq_elements[ekey], self._freq_stoich[skey])
            if f <= self.k_inter_low:
                r_inter = 2.0
            elif f <= self.k_inter_high:
                r_inter = 1.0
            else:
                r_inter = 0.0

            results[i].r_match = r_match
            results[i].r_intra = r_intra
            results[i].r_inter = r_inter
            results[i].r_div = r_match + r_intra + r_inter

            seen_structures.append(s)
            elem_counter[ekey] += 1
            stoich_counter[skey] += 1
            # Update persistent cross-rollout counters AFTER scoring this structure.
            self._freq_elements[ekey] += 1
            self._freq_stoich[skey] += 1
